/* ═══════════════ SHARED MENU DATA ═══════════════
   Used by BOTH admin.js and menu.html.
   One source of truth for all dishes.
   Add/edit here → updates everywhere. */
const MENU_DATA = [
  // ── MUTTON BIRYANI ──
  { name:"Mutton Biryani Single", desc:"A generous single portion of slow-cooked mutton and fragrant basmati", price:220, img:"images/placeholder.svg", cat:"mutton-biryani" },
  { name:"Mutton Biryani Full", desc:"Full plate — two pieces of tender mutton, sealed with dough and baked", price:380, img:"images/placeholder.svg", cat:"mutton-biryani" },
  { name:"Mutton Biryani Double Ghosh", desc:"Double the meat, double the joy — four pieces of premium mutton", price:520, img:"images/placeholder.svg", cat:"mutton-biryani" },
  { name:"Mutton Biryani Family Pack (4)", desc:"Serves four — the perfect gathering of family around the biryani pot", price:800, img:"images/placeholder.svg", cat:"mutton-biryani" },
  { name:"Mutton Biryani Jumbo Pack (5)", desc:"The feast size — five generous portions for the true biryani lover", price:1100, img:"images/placeholder.svg", cat:"mutton-biryani" },
  // ── SPECIAL MUTTON ──
  { name:"Mutton Fry Piece Biryani", desc:"Crispy fried mutton pieces layered with aromatic rice and caramelised onions", price:450, img:"images/placeholder.svg", cat:"special-mutton" },
  { name:"Mutton Moghlai Biryani", desc:"Royal Mughal recipe — saffron, dry fruits, and slow-braised mutton", price:480, img:"images/placeholder.svg", cat:"special-mutton" },
  { name:"Mutton Kheema Biryani", desc:"Minced mutton cooked with whole spices, layered with long-grain basmati", price:550, img:"images/placeholder.svg", cat:"special-mutton" },
  { name:"Mutton Nallighosh Biryani", desc:"Hyderabadi specialty — tender lamb shanks falling off the bone", price:600, img:"images/placeholder.svg", cat:"special-mutton" },
  // ── CHICKEN BIRYANI ──
  { name:"Chicken Biryani Single", desc:"One piece of juicy chicken, perfectly spiced for a solo indulgence", price:160, img:"images/placeholder.svg", cat:"chicken-biryani" },
  { name:"Chicken Biryani Full", desc:"Two pieces of chicken, sealed and slow-cooked in the traditional dum style", price:280, img:"images/placeholder.svg", cat:"chicken-biryani" },
  { name:"Chicken Extra Piece", desc:"Add an extra piece of our signature chicken to any biryani", price:60, img:"images/placeholder.svg", cat:"chicken-biryani" },
  { name:"Chicken Biryani Family Pack", desc:"Serves four — share the love, share the biryani", price:600, img:"images/placeholder.svg", cat:"chicken-biryani" },
  { name:"Chicken Biryani Jumbo Pack (5)", desc:"Five full portions — for when the whole gang is hungry", price:750, img:"images/placeholder.svg", cat:"chicken-biryani" },
  { name:"Egg Biryani", desc:"Boiled eggs nestled in spiced rice — simple, satisfying, sublime", price:200, img:"images/placeholder.svg", cat:"chicken-biryani" },
  // ── SPECIAL CHICKEN ──
  { name:"Chicken 65 Biryani (Half)", desc:"Spicy Chicken 65 pieces tossed with biryani rice — half", price:180, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken 65 Biryani (Full)", desc:"Spicy Chicken 65 pieces tossed with biryani rice — full", price:300, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken Boneless Biryani (Half)", desc:"Tender boneless chicken, saffron rice — half", price:220, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken Boneless Biryani (Full)", desc:"Tender boneless chicken, saffron rice — full", price:350, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken Fry Piece Biryani (Half)", desc:"Crispy fried chicken pieces with aromatic rice — half", price:200, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken Fry Piece Biryani (Full)", desc:"Crispy fried chicken pieces with aromatic rice — full", price:320, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken Lollipop Biryani", desc:"Chicken lollipops perched on a bed of spiced biryani rice", price:320, img:"images/placeholder.svg", cat:"special-chicken" },
  { name:"Chicken Moghlai Biryani", desc:"Mughal-inspired — dry fruits, cream, and saffron with tender chicken", price:350, img:"images/placeholder.svg", cat:"special-chicken" },
  // ── SEA FOOD ──
  { name:"Fish Biryani", desc:"Fresh catch of the day, marinated in coastal spices and layered with rice", price:320, img:"images/placeholder.svg", cat:"seafood-biryani" },
  { name:"Prawns Biryani", desc:"Juicy prawns in a fragrant masala, slow-cooked with basmati", price:350, img:"images/placeholder.svg", cat:"seafood-biryani" },
  { name:"MLA Potlam Biryani", desc:"Mutton, chicken, and prawns in one grand potlam", price:480, img:"images/placeholder.svg", cat:"seafood-biryani" },
  // ── VEG BIRYANI ──
  { name:"Veg Biryani", desc:"Garden-fresh vegetables, slow-cooked with whole spices and basmati", price:200, img:"images/placeholder.svg", cat:"veg-biryani" },
  { name:"Veg Manchurian Biryani", desc:"Indo-Chinese fusion — crispy Manchurian balls meet biryani rice", price:240, img:"images/placeholder.svg", cat:"veg-biryani" },
  { name:"Veg Paneer Biryani", desc:"Soft paneer cubes in spiced rice", price:260, img:"images/placeholder.svg", cat:"veg-biryani" },
  { name:"Veg Mushroom Biryani", desc:"Earthy mushrooms and aromatic rice", price:280, img:"images/placeholder.svg", cat:"veg-biryani" },
  { name:"Kaju Biryani", desc:"Rich cashew nuts and vegetables in creamy spiced rice", price:300, img:"images/placeholder.svg", cat:"veg-biryani" },
  { name:"Mixed Veg Biryani", desc:"The best of the garden — mixed vegetables in a festive biryani", price:300, img:"images/placeholder.svg", cat:"veg-biryani" },
  // ── NON VEG STARTERS ──
  { name:"Chicken 65", desc:"Classic spicy deep-fried chicken starter", price:240, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Manchuria", desc:"Indo-Chinese chicken Manchurian", price:240, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chilli Chicken", desc:"Spicy chilli chicken stir-fry", price:250, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Drumsticks", desc:"Crispy fried chicken drumsticks", price:280, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Drums of Heaven", desc:"Spicy Indo-Chinese chicken drums", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Lollipop", desc:"Crispy chicken lollipops", price:280, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Pepper Chicken", desc:"Black pepper chicken dry fry", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Majestic", desc:"Hyderabadi-style creamy spicy chicken", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken 555", desc:"Crispy fried chicken special", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Lemon Chicken", desc:"Tangy lemon-flavoured chicken", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Cashew Chicken", desc:"Chicken with crunchy cashew nuts", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Schezwan Chicken", desc:"Spicy Schezwan-style chicken", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Ginger Chicken", desc:"Ginger-infused chicken stir-fry", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Garlic Chicken", desc:"Garlicky chicken dry fry", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Hongkong", desc:"Hong Kong-style chicken", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Hunan Chicken", desc:"Hunan-style spicy chicken", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken 8 To 8", desc:"Special marinated chicken fry", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Honey Chilli Chicken", desc:"Sweet & spicy honey chilli chicken", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Dragon Chicken", desc:"Dragon-style fried chicken", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chicken Rampuri", desc:"Rampuri-style spicy chicken", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Apollo Chicken", desc:"Andhra-style Apollo chicken", price:340, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Sholay Chicken", desc:"Fiery Sholay-style chicken", price:350, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Bangla Kodi Chips", desc:"Crispy Bangla-style chicken chips", price:350, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Lucky's Special Chicken", desc:"Our signature house special chicken", price:380, img:"images/placeholder.svg", cat:"nonveg-starters" },
  // ADDITIONAL NV STARTERS
  { name:"Mutton 65", desc:"Spicy deep-fried mutton starter", price:350, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Mutton Chilli", desc:"Chilli mutton dry fry", price:350, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Pepper Mutton", desc:"Black pepper mutton fry", price:380, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Mutton Kheema Balls", desc:"Spiced minced mutton balls", price:430, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chilli Fish", desc:"Spicy chilli fish fry", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Apollo Fish", desc:"Andhra-style Apollo fish", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Pepper Fish", desc:"Black pepper fish fry", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Fish Fingers", desc:"Crispy fish fingers", price:340, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Fish 65", desc:"Spicy fish 65 fry", price:300, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Chilli Prawns", desc:"Spicy chilli prawns", price:320, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Loose Prawns", desc:"Crispy fried loose prawns", price:350, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Egg Chilli", desc:"Spicy egg chilli fry", price:160, img:"images/placeholder.svg", cat:"nonveg-starters" },
  { name:"Egg 65", desc:"Egg 65-style fry", price:160, img:"images/placeholder.svg", cat:"nonveg-starters" },
  // ── VEG STARTERS ──
  { name:"Veg Manchuria", desc:"Indo-Chinese veg Manchurian", price:200, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Chilli Mushroom", desc:"Spicy chilli mushroom", price:220, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Mushroom 65", desc:"Mushroom 65-style fry", price:220, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Pepper Mushroom", desc:"Black pepper mushroom", price:240, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Chilli Babycorn", desc:"Spicy chilli babycorn", price:220, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Pepper Babycorn", desc:"Black pepper babycorn", price:240, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Gobi Manchuria", desc:"Cauliflower Manchurian", price:180, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Paneer 65", desc:"Paneer 65-style fry", price:240, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Dragon Paneer", desc:"Dragon-style fried paneer", price:250, img:"images/placeholder.svg", cat:"veg-starters" },
  { name:"Paneer Majestic", desc:"Hyderabadi-style creamy paneer", price:260, img:"images/placeholder.svg", cat:"veg-starters" },
  // ── VEG CURRIES ──
  { name:"Paneer Butter Masala", desc:"Classic rich paneer butter masala", price:220, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Kadai Paneer", desc:"Paneer cooked in kadai with peppers", price:220, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Shahi Paneer", desc:"Royal creamy paneer curry", price:250, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Paneer Tikka Masala", desc:"Tandoori paneer tikka in masala gravy", price:250, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Palak Paneer", desc:"Paneer in creamy spinach gravy", price:240, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Paneer Chatpat", desc:"Tangy chatpata paneer curry", price:280, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Kaju Paneer", desc:"Rich cashew and paneer curry", price:350, img:"images/placeholder.svg", cat:"veg-curries" },
  { name:"Mushroom Masala", desc:"Mushroom in spiced masala gravy", price:240, img:"images/placeholder.svg", cat:"veg-curries" },
  // ── NON VEG CURRIES ──
  { name:"Egg Masala", desc:"Boiled eggs in spicy masala gravy", price:150, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Butter Chicken", desc:"Classic butter chicken curry", price:240, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Kadai Chicken", desc:"Chicken cooked in kadai with peppers", price:240, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Methi Chicken", desc:"Chicken with fenugreek leaves", price:240, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Chicken Kolhapuri", desc:"Maharashtrian spicy chicken curry", price:250, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Chicken Tikka Masala", desc:"Tandoori chicken tikka in masala gravy", price:280, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Punjabi Chicken", desc:"Rich Punjabi-style chicken curry", price:260, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Telangana Chicken", desc:"Telangana-style spicy chicken", price:250, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Andhra Chicken", desc:"Andhra-style fiery chicken curry", price:250, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Chicken Rara", desc:"Minced chicken in rich gravy", price:280, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Dum Ka Chicken", desc:"Slow dum-cooked chicken curry", price:280, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Afghani Chicken", desc:"Creamy Afghani-style chicken", price:280, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Mutton Kheema", desc:"Spiced minced mutton curry", price:380, img:"images/placeholder.svg", cat:"nonveg-curries" },
  { name:"Mutton Rogan Ghosh", desc:"Kashmiri-style mutton curry", price:380, img:"images/placeholder.svg", cat:"nonveg-curries" },
  // ── ROTIS ──
  { name:"Rumali Roti", desc:"Thin, soft handkerchief bread", price:15, img:"images/placeholder.svg", cat:"rotis" },
  { name:"Tandoori Roti", desc:"Clay oven-baked whole wheat bread", price:20, img:"images/placeholder.svg", cat:"rotis" },
  { name:"Plain Naan", desc:"Soft leavened flatbread", price:30, img:"images/placeholder.svg", cat:"rotis" },
  { name:"Butter Naan", desc:"Naan topped with butter", price:40, img:"images/placeholder.svg", cat:"rotis" },
  { name:"Garlic Naan", desc:"Naan with garlic and butter", price:50, img:"images/placeholder.svg", cat:"rotis" },
  // ── RICE ──
  { name:"Jeera Rice", desc:"Cumin-flavoured basmati rice", price:140, img:"images/placeholder.svg", cat:"rice" },
  { name:"Ghee Rice", desc:"Fragrant rice cooked with ghee", price:160, img:"images/placeholder.svg", cat:"rice" },
  { name:"Curd Rice", desc:"Cooling curd rice tempered with mustard", price:120, img:"images/placeholder.svg", cat:"rice" },
  // ── RICE / NOODLES ──
  { name:"Veg Fried Rice", desc:"Classic vegetable fried rice", price:140, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Mushroom Fried Rice", desc:"Mushroom fried rice", price:160, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Paneer Fried Rice", desc:"Paneer fried rice", price:170, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Egg Fried Rice", desc:"Egg fried rice", price:140, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Chicken Fried Rice", desc:"Chicken fried rice", price:200, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Chicken Schezwan Fried Rice", desc:"Spicy Schezwan chicken fried rice", price:220, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Prawn Fried Rice", desc:"Prawn fried rice", price:250, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Mixed Non Veg Fried Rice", desc:"Mixed non-veg fried rice", price:280, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Veg Soft Noodles", desc:"Soft vegetable noodles", price:140, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Veg Schezwan Noodles", desc:"Spicy Schezwan veg noodles", price:150, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Veg Chilli Garlic Noodles", desc:"Chilli garlic veg noodles", price:180, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Egg Noodles", desc:"Egg noodles", price:140, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Chicken Soft Noodles", desc:"Soft chicken noodles", price:200, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Chicken Schezwan Noodles", desc:"Spicy Schezwan chicken noodles", price:220, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Chicken Chilli Garlic Noodles", desc:"Chilli garlic chicken noodles", price:250, img:"images/placeholder.svg", cat:"rice-noodles" },
  { name:"Mixed Non Veg Noodles", desc:"Mixed non-veg noodles", price:280, img:"images/placeholder.svg", cat:"rice-noodles" },
  // ── TANDOORI ──
  { name:"Hara Bara Kebab", desc:"Green vegetable kebab", price:220, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Paneer Tikka", desc:"Tandoori paneer tikka", price:250, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Malai Broccoli Tikka", desc:"Creamy malai broccoli tikka", price:300, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Tandoori Chicken (Half)", desc:"Classic tandoori chicken — half", price:200, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Tandoori Chicken (Full)", desc:"Classic tandoori chicken — full", price:380, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Tangdi Kebab (Half)", desc:"Chicken leg kebab — half", price:200, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Tangdi Kebab (Full)", desc:"Chicken leg kebab — full", price:380, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Chicken Tikka", desc:"Boneless tandoori chicken tikka", price:280, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Angara Kebab", desc:"Smoked spicy chicken kebab", price:280, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Hariyali Kebab", desc:"Green herb-marinated chicken kebab", price:280, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Murgh Malai Kebab", desc:"Creamy chicken malai kebab", price:320, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Mutton Sheekh Kebab", desc:"Spiced minced mutton sheekh kebab", price:440, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Mutton Galouti Kebab", desc:"Melt-in-mouth Lucknowi mutton kebab", price:450, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Fish Tikka", desc:"Tandoori fish tikka", price:320, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Fish Malai Tikka", desc:"Creamy malai fish tikka", price:340, img:"images/placeholder.svg", cat:"tandoori" },
  { name:"Tandoori Prawns", desc:"Tandoori-spiced prawns", price:350, img:"images/placeholder.svg", cat:"tandoori" },
];
